### ISSUE TITLE
plan_nfft CPU/GPU performances

### ISSUE THREAD

**Issue by grizzuti** [JuliaMath/NFFT.jl#67]
Dear all, first things first: thanks a lot for this pure Julia implementation of NFFT, which is going to be quite useful for my line of work.

I noticed some discrepancies in the plan_nfft function in terms of computations for the CPU and GPU implementation. For my application, it is important to replan at every NFFT evaluation and its computational overhead is therefore crucial.

Find below a code snippet where you can compare timings for plan_nfft with CPU and GPU (by commenting/uncommenting the flag_gpu line):
```
using NFFT, BenchmarkTools, Flux, CUDA
CUDA.allowscalar(false)

# Select CPU/GPU
flag_gpu = true
# flag_gpu = false
device = flag_gpu ? NFFT.CUDAGPU : NFFT.CPU

# 3D k-space coordinates
n = (64, 64, 64)
# n = (128, 128, 128)
dk = 1f0./n
kx = collect(range(-0.5f0, 0.5f0; length=n[1])).*dk[1]
ky = collect(range(-0.5f0, 0.5f0; length=n[2])).*dk[2]
kz = collect(range(-0.5f0, 0.5f0; length=n[3])).*dk[3]
Kx = repeat(kx;                   outer=(1,n[2],n[3])); flag_gpu && (Kx = Kx |> gpu)
Ky = repeat(ky';                  outer=(n[1],1,n[3])); flag_gpu && (Ky = Ky |> gpu)
Kz = repeat(reshape(kz,1,1,n[3]); outer=(n[1],n[2],1)); flag_gpu && (Kz = Kz |> gpu)
k = [vec(Kx)'; vec(Ky)'; vec(Kz)']

# Input
u = randn(ComplexF32, n); flag_gpu && (u = u |> gpu)

# NFFT
@btime plan_nfft(k, n; device=device)
p = plan_nfft(k, n; device=device)
@btime U = nfft(p, u);
```

On my laptop, plan_nfft takes about 1.7 ms on CPU, and 7.22 s on GPU, which is perhaps indicative of something not quite right.
Please, let me know if I'm overlooking something here.

Regards,
Gabrio

**Comment by tknopp** [comment]
Thanks for the report. I have rewritten the GPU part in the last days and one https://github.com/JuliaRegistries/General/pull/51965
I would request you to test this again.

We then need to fix the performance problems step by step. I hope that we are already faster since the old code was not type stable.

Do you need to do just one NFFT or can you do several with the same plan?

**Comment by grizzuti** [comment]
The results I was posting above also include the latest changes.

Regarding the plan re-usage, it is quite limited; I use the same plan for exactly 3 evaluations + adjoint in 3D (related to first-order optimization).

**Comment by tknopp** [comment]
Your code listed above is not compatible with NFFT version 0.7. There is no option `device=device` anymore. Instead on passes the array type as the first argument, see https://github.com/tknopp/NFFT.jl/blob/master/CuNFFT/src/implementation.jl#L19
Once CuNFFT is registered you can just add it. Right now you need to dev it from the local path: `dev ~/.julia/dev/NFFT/CuNFFT`. This requires that NFFT is dev-ed as well.

**Comment by grizzuti** [comment]
You're right, I was indeed using the 0.6.x version. Following the instructions you gave on using the dev version, I'm able to create a nfft plan, but the actual evaluation of nfft gives now an error (and a warning), for example:
```
using CuNFFT, BenchmarkTools, Flux, CUDA
CUDA.allowscalar(false)

# 3D k-space coordinates
n = (64, 64, 64)
M = 2^10
k = randn(Float32, 3, M)

# Input
u = randn(ComplexF32, n) |> gpu

# NFFT
p = plan_nfft(CuArray, k, n)
U = nfft(p, u)
```
with output:
```
ERROR: LoadError: DimensionMismatch("WARNING: both NFFT and AbstractNFFTs export "nodes!"; uses of it in module CuNFFT must be qualified
X must have length 0, but has length 2097152")
```

**Comment by tknopp** [comment]
Thank you that was indeed a problem with the new code. I fixed that and made some benchmarks:

```julia
julia> @btime p = plan_nfft(CuArray, k, n);
  11.881 ms (5956 allocations: 42.64 MiB)

julia> @btime U = nfft(p, u);
  5.749 ms (93 allocations: 3.84 KiB)

julia> @btime p = plan_nfft(Array, k, n);
  3.403 ms (318 allocations: 32.70 MiB)

julia> @btime U = nfft(p, u);
  70.718 ms (3075 allocations: 80.16 KiB)
```

The 11 ms is still more but now we are in the right range. Now it would of course be interesting where those 11 ms are spend. Probably this is memory transfer to the GPU. One would need to profile that. Another issue is that the CuNFFTPlan is right now not type stable. There are thus some opportunities to improve the speed.

**Comment by grizzuti** [comment]
I was waiting for the registration of CuNFFT.jl. The computational times for planning are now more than enough for my scopes, thanks! However, I still get the same error listed above when evaluating the nfft, not sure why:
```
ERROR: DimensionMismatch("X must have length 0, but has length 16777216")
Stacktrace:
  [1] chkmvdims(X::CuArray{ComplexF32, 1, CUDA.Mem.DeviceBuffer}, n::Int64, Y::CuArray{ComplexF32, 1, CUDA.Mem.DeviceBuffer}, m::Int64)
    @ CUDA.CUSPARSE ~/.julia/packages/CUDA/sCev8/lib/cusparse/util.jl:8
  [2] mv!(transa::Char, alpha::Bool, A::CUDA.CUSPARSE.CuSparseMatrixCSC{ComplexF32, Int32}, X::CuArray{ComplexF32, 1, CUDA.Mem.DeviceBuffer}, beta::Bool, Y::CuArray{ComplexF32, 1, CUDA.Mem.DeviceBuffer}, index::Char)
    @ CUDA.CUSPARSE ~/.julia/packages/CUDA/sCev8/lib/cusparse/generic.jl:125
  [3] mv_wrapper
    @ ~/.julia/packages/CUDA/sCev8/lib/cusparse/interfaces.jl:8 [inlined]
  [4] mul!(C::CuArray{ComplexF32, 1, CUDA.Mem.DeviceBuffer}, A::LinearAlgebra.Transpose{ComplexF32, CUDA.CUSPARSE.CuSparseMatrixCSC{ComplexF32, Int32}}, B::CuArray{ComplexF32, 1, CUDA.Mem.DeviceBuffer}, alpha::Bool, beta::Bool)
    @ CUDA.CUSPARSE ~/.julia/packages/CUDA/sCev8/lib/cusparse/interfaces.jl:41
  [5] mul!
    @ ~/GATechBundle/Julia/julia-1.7.1/share/julia/stdlib/v1.7/LinearAlgebra/src/matmul.jl:275 [inlined]
  [6] nfft!(p::CuNFFT.CuNFFTPlan{Float32, 3}, f::CuArray{ComplexF32, 3, CUDA.Mem.DeviceBuffer}, fHat::CuArray{ComplexF32, 1, CUDA.Mem.DeviceBuffer})
    @ CuNFFT ~/.julia/packages/CuNFFT/C0ABY/src/implementation.jl:77
  [7] nfft(::CuNFFT.CuNFFTPlan{Float32, 3}, ::CuArray{ComplexF32, 3, CUDA.Mem.DeviceBuffer}; kargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ AbstractNFFTs ~/.julia/packages/AbstractNFFTs/fpyMI/src/derived.jl:59
  [8] nfft(::CuNFFT.CuNFFTPlan{Float32, 3}, ::CuArray{ComplexF32, 3, CUDA.Mem.DeviceBuffer})
    @ AbstractNFFTs ~/.julia/packages/AbstractNFFTs/fpyMI/src/derived.jl:58
  [9] top-level scope
    @ REPL[11]:1
 [10] top-level scope
    @ ~/.julia/packages/CUDA/sCev8/src/initialization.jl:52


```

**Comment by tknopp** [comment]
This is because I registered first and then fixed the bug. Because the registration period takes 3-4 days I needed to wait. But now I can do the release that fixes the bug.

**Comment by tknopp** [comment]
Closing this now since our planner is now much faster on the GPU.
